server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: shoppingCart-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingCart_service?serverTimezone=UTC
    username: root
    password: 123456789

resilience4j.circuitbreaker:
  instances:
    productServiceCircuitBreaker:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      recordExceptions:
        - com.oesdev.shoppingCart_service.exception.ShoppingCartNotFoundException
        - feign.FeignException
management:
  endpoints:
    web:
      exposure:
        include: resilience4j.circuitbreakers
